Wysiwyg nav layout - Popover position
strapi/parts pull request #233
Opened 2021-08-09 09:29 UTC by ronronscelestes

## What
Added popover component when clicking on "more actions" button.

## What is the issue
Popover's position doesn't fit with the mock up : 
- Should we change the popover's default position to be centered in reference of the source element?
- Should we change the popover's default position to be closer to the source element (4px)?
- Should we do something about the extra pixels right side of the popover when we don't want it to have a scrolling behavior?

## Demo 

What it looks like when we integrate the popover to the wysiwyg:
<img width="583" alt="Capture d’écran 2021-08-06 à 17 44 44" src="https://user-images.githubusercontent.com/71838159/128685743-5c22bbfe-2321-45d5-8892-e4c647e27119.png">

What it should looks like:
<img width="394" alt="Capture d’écran 2021-08-09 à 11 29 38" src="https://user-images.githubusercontent.com/71838159/128685878-584ce0b2-e554-46c3-888b-9f374c7c9c13.png">

2021-08-09 09:41 UTC, maevalienard commented
If this was just me, I would answer "yes" to all the questions, so I'll let the other devs answer :)

2021-08-09 09:42 UTC, mfrachet commented
> Should we change the popover's default position to be centered in reference of the source element?

I don't think we should change the default position of the Popover. However, what we could do is to pass a "centered" props to the popover and position it accordingly on the screen, only when it's passed 😊

> Should we change the popover's default position to be closer to the source element (4px)?

Nope, the popover is used in other places 😊 . However, you have a `spacingTop` that accepts a spacing (defined in the spaces scale) if you want to grow / reduce the space. The minimum value in this scale is 0 and then it's 4 :D . We will never accept a change on that scale except if it's a group decision 😊 


> Should we do something about the extra pixels right side of the popover when we don't want it to have a scrolling behavior?

It's because of an overflow-y necessary for the select component 😅 . We can try to make tests without this one

2021-08-09 09:49 UTC, maevalienard commented
> We will never accept a change on that scale except if it's a group decision 😊

The spacing between an object and the popOver in the design is always 4px :)

2021-08-09 09:52 UTC, ronronscelestes commented
> I don't think we should change the default position of the Popover. However, what we could do is to pass a "centered" props to the popover and position it accordingly on the screen, only when it's passed 😊
Sure, should I create a branch for it and start on trying to make it work this way?

> Nope, the popover is used in other places 😊 . However, you have a `spacingTop` that accepts a spacing 
Perfect I just used spacingTop={1} and it works like a charm

> It's because of an overflow-y necessary for the select component 😅 . We can try to make tests without this one
Should we have a prop for this new behaviour too so it could keep its overflow-y "default" behavior? Or do you mean that we should try to erase the scroll y effect completely?

2021-08-09 09:54 UTC, mfrachet commented
> Sure, should I create a branch for it and start on trying to make it work this way?

Yup, if you don't have a focus on something else, that would be awesome 😊 

> Should we have a prop for this new behaviour too so it could keep its overflow-y "default" behavior? Or do you mean that we should try to erase the scroll y effect completely?

I think we should try first and see if the overflow still works when used in the Select component (the infinite list one) and then take a decision :)

2021-08-09 10:03 UTC, ronronscelestes commented
> Yup, if you don't have a focus on something else, that would be awesome 😊

My focus is the Wysiwyg so, I'm on it 🤗

> I think we should try first and see if the overflow still works when used in the Select component (the infinite list one) and then take a decision :)

Okay I might do a PR only for the centering issue first then will see for the overflow issue when the first one is good for us!

2021-08-12 17:41 UTC, HichamELBSI requested changes

2021-08-12 17:41 UTC, HichamELBSI commented on example/src/shared/Wysiwyg/WysiwygNav.js
> +const WysiwygNav = ({
In this component, you do 13 times the condition `isPreviewMode ? true : false`. Also, you don't event need to render the popover on preview mode.

You can do the condition only one time before the render:
```jsx
const WysiwygNav = ({ ..., isPreviewMode }) => {
   const buttonMoreRef = useRef();

   if (isPreviewMode) {
       return (
           <NavWrapper padding={2} background="neutral100">
              <Row justifyContent="space-between">
                <Row>
                  <Select
                    disabled
                    id="selectTitle"
                    placeholder={placeholder}
                    size="S"
                    onChange={(value) => onActionClick(value)}
                  >
                    <Option value="h1">h1</Option>
                    <Option value="h2">h2</Option>
                    <Option value="h3">h3</Option>
                    <Option value="h4">h4</Option>
                    <Option value="h5">h5</Option>
                    <Option value="h6">h6</Option>
                  </Select>
      
                  <MainButtons>
                    <CustomIconButton disabled id="Bold" label="Bold" name="Bold" icon={<Bold />} />
                    <CustomIconButton disabled id="Italic" label="Italic" name="Italic" icon={<Italic />} />
                    <CustomIconButton disabled id="Underline" label="Underline" name="Underline" icon={<Underline />} />
                  </MainButtons>
      
                  <MoreButton disabled id="more" label="more" icon={<More />} />
                </Row>
      
                <Button onClick={() => setIsPreviewMode((prev) => !prev)} variant="tertiary" size="L" id="preview">
                  Markdown mode
                </Button>
              </Row>
            </NavWrapper>
       );
   }

   return (
      // render the editable mode :)
   )
}
```

2021-08-13 15:22 UTC, ronronscelestes commented on example/src/shared/PreviewWysiwyg/Wrapper.js
> +  height: 100%; */
This one I would like to uncomment it but I left there it to let @mfrachet check that the editor isn't tableable when on preview mode!

2021-08-13 15:24 UTC, ronronscelestes commented on example/src/shared/PreviewWysiwyg/Wrapper.js
> +  padding: 12px 17px 0 17px;
Oh right, on it!

2021-08-16 08:38 UTC, HichamELBSI commented on example/src/shared/Wysiwyg/Editor.js
> +import PreviewWysiwyg from './../PreviewWysiwyg/index'
You don't need the `/index` (node.js will search and load (by default) an index.js file from the folder).
You don't need the `./` (When you import a module from a higher directory)

```js
import PreviewWysiwyg from '../PreviewWysiwyg';
```

2021-08-20 06:26 UTC, soupette requested changes
I have tested it and it works great well done!

In another PR can you insert the `code block` and `quote` markups on a new line instead of the current one?

2021-08-20 06:26 UTC, soupette commented on example/src/shared/PreviewWysiwyg/Wrapper.js
>  /* eslint-disable */
I think you can remove this override.

2021-08-20 06:26 UTC, soupette commented on example/src/shared/Wysiwyg/WysiwygNav.js
> +              Markdown mode
Can you add a comment so we remember to put formatMessage when migrating to code in strapi?

2021-08-20 06:26 UTC, soupette commented on example/src/shared/Wysiwyg/WysiwygNav.js
> +          Preview mode
Same here

2021-08-20 06:26 UTC, soupette commented on example/src/shared/Wysiwyg/_test_/Wysiwyg.spec.js
> +describe("Wysiwyg render and actions buttons", () => {
Good job!

2021-08-24 13:40 UTC, soupette approved these changes
LGTM!

2021-08-24 13:41 UTC, merged