MainNav notifications
strapi/parts pull request #307
Opened 2021-09-01 09:48 UTC by ronronscelestes

## What / Why

Added notifications props to MainNav/NavLink

## Demo

<img width="295" alt="Capture d’écran 2021-09-01 à 11 47 34" src="https://user-images.githubusercontent.com/71838159/131650454-1bdeed72-0085-4d48-8ff2-74228ad73b78.png">
<img width="116" alt="Capture d’écran 2021-09-01 à 11 47 45" src="https://user-images.githubusercontent.com/71838159/131650469-f9fb1e3b-b3d8-4714-831a-eff021de5543.png">

2021-09-01 11:06 UTC, soupette approved these changes
LGTM

2021-09-01 11:56 UTC, bulby97 requested changes

2021-09-01 11:56 UTC, bulby97 commented on packages/strapi-parts/src/MainNav/NavLink.js
> +  //positionning when condensed
You can group css prop depending on a specific state by using a function returning a template string

```
  ${({ condensed }) => `
    position: absolute;
    transform: translate(35%, -50%);
    ...
`}
```

2021-09-01 12:01 UTC, bulby97 requested changes

2021-09-01 12:01 UTC, bulby97 commented on packages/strapi-parts/src/MainNav/NavLink.js
> +  right: ${(props) => (props.condensed ? '0' : '')};
```suggestion
  ${({ condensed }) =>  condensed && `
    position: absolute;
    transform: translate(35%, -50%)
    top: 0;
    right: 0;
  `}
```

2021-09-01 13:53 UTC, HichamELBSI requested changes
Good job :)

2021-09-01 13:53 UTC, HichamELBSI commented on packages/strapi-parts/src/MainNav/NavLink.js
> +    line-height: 0;
I don't really understand why you need the  `line-height: 0;`

2021-09-01 13:53 UTC, HichamELBSI commented on packages/strapi-parts/src/MainNav/NavLink.js
> +  const isNotification = notifications > 0;
Notifications is a feature. The Parts components should not refer to a feature. Can you rename everything that refers to notifications into something more neutral. Best for this case would be: Badge. 
`notifications -> badgeContent`
`isNotification -> withBadge`

2021-09-01 13:53 UTC, HichamELBSI commented on packages/strapi-parts/src/MainNav/NavLink.js
> +`;
Can you use the existing Badge component please and a badge wrapper.
```suggestion
const BadgeWrapper = styled(Row)`
  //positionning when condensed
  ${({ condensed }) =>  condensed && `
	position: absolute;
	transform: translate(35%, -50%);
	top: 0;
	right: 0;
   `}

  ${Text} {
    color: ${({ theme }) => theme.colors.neutral0} !important;
  }
`;
const CustomBadge = styled(Badge)`
  height: ${({ theme }) => theme.spaces[5]};
  padding: ${({ theme }) => `0 ${theme.spaces[2]}`};
  border-radius: ${({ theme }) => theme.spaces[10]};
`;
```

2021-09-01 13:53 UTC, HichamELBSI commented on packages/strapi-parts/src/MainNav/NavLink.js
> +`;
Can you also add a comment above the !important please. We need to find a solution to avoid that bad practice.

2021-09-01 13:53 UTC, HichamELBSI commented on packages/strapi-parts/src/MainNav/NavLink.js
> +          )}
```suggestion
          {isNotification && (
            <BadgeWrapper justifyContent="center">
              <CustomBadge backgroundColor="primary600">
                <Text aria-label={badgeAriaLabel} small highlighted>
                  {notifications}
                </Text>
              </CustomBadge>
            </BadgeWrapper>
          )}
```

2021-09-01 13:53 UTC, HichamELBSI commented on packages/strapi-parts/src/MainNav/NavLink.js
> +                </Notification>
```suggestion
                <BadgeWrapper condensed justifyContent="center">
                  <CustomBadge backgroundColor="primary600">
                    <Text aria-label={badgeAriaLabel} small highlighted>
                      {notifications}
                    </Text>
                  </CustomBadge>
                </BadgeWrapper>
```

2021-09-01 13:53 UTC, HichamELBSI commented on packages/strapi-parts/src/MainNav/NavLink.js
> +  notifications: PropTypes.number,
It can be a string or a  number

2021-09-01 13:53 UTC, HichamELBSI commented on packages/strapi-parts/src/MainNav/NavLink.js
> +  const isNotification = notifications > 0;
Can you also add a `badgeAriaLabel` in order to give a custom aria-label to the badge. If you enable the screen reader in the Storybook, it says "Settings 2". We need to give more information about the badge.

2021-09-02 08:12 UTC, HichamELBSI requested changes

2021-09-02 08:12 UTC, HichamELBSI commented on packages/strapi-parts/src/MainNav/MainNav.stories.mdx
> +                <NavLink to="/content" badgeContent={'1'} icon={<MarketPlaceIcon />} badgeAriaLabel="notifications">
In my opinion, for the notification case, the badgeAriaLabel should be
`badgeAriaLabel={${numberOfNotification} notification(s).}`

Also, the badgeContent for the notification case should be a number `badgeContent={1}`

2021-09-02 14:05 UTC, HichamELBSI approved these changes
LGTM

2021-09-02 14:05 UTC, merged